# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch, minor, major)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.repository_owner == 'fabric8-analytics'
    name: Prepare a release
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .npmrc
        run: |
          echo "@trustification:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "@fabric8-analytics:registry=https://npm.pkg.github.com" >> ~/.npmrc
      
      - name: Install @vscode/vsce
        run: npm i -g @vscode/vsce

      - name: Install Dependencies
        run: npm ci

      - name: Update package with new version
        id: bump
        run: |
          new_version=$(npm version ${{ github.event.inputs.version_bump }} --no-git-tag-version)
          echo "version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Compile for test
        run: npm run test-compile

      - name: VSCE package
        run: vsce package --out fabric8-analytics-${{ steps.bump.outputs.version }}-${{ github.run_number }}.vsix

      - name: Create SHA256 checksum
        run: |
          sha256sum fabric8-analytics-${{ steps.bump.outputs.version }}-${{ github.run_number }}.vsix > fabric8-analytics-${{ steps.bump.outputs.version }}-${{ github.run_number }}.vsix.sha256

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create release branch
        run: |
          git checkout -b release/${{ steps.bump.outputs.version }}

      - name: Create release notes from changelog
        id: release-notes
        run: |
          version="${{ steps.bump.outputs.version }}"
          version=${version#v}
          changelog_header=$(grep "## $version" ./CHANGELOG.md || true)
          if [ -z "$changelog_header" ]; then
            echo "Release notes are missing for version $version."
            exit 1
          fi

      - name: Commit changes
        run: |
          git add package.json
          git add package-lock.json
          git commit -m "[release] ${{ steps.bump.outputs.version }}"

      - name: Push changes
        run: |
          git push origin release/${{ steps.bump.outputs.version }}

      - name: Create & Merge Pull Request
        run: |
          gh label create "${{ steps.bump.outputs.version }}" --force
          gh pr create \
            --base main \
            --title "[release] ${{ steps.bump.outputs.version }}" \
            --body "$PR_BODY" \
            --head release/${{ steps.bump.outputs.version }} \
            --label "release" --label "${{ steps.bump.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BODY: |
            This PR contains the changes for release ${{ steps.bump.outputs.version }}.
            
            Changes:
            - Updated version in package.json

      